/**
 * Bibliography of the research programme, numbered exactly as in the proposal (v1.2) so that every
 * citation on the docs pages matches the PDF. Entries without a public page are FabricVTON's internal
 * documents; they are listed for completeness and available to reviewers on request.
 */

export type DocRef = { text: string; url?: string };

const arxiv = (id: string) => `https://arxiv.org/abs/${id}`;

export const DOC_REFS: Record<number, DocRef> = {
  1: { text: "Coresight Research. The True Cost of Apparel Returns: Alarming Return Rates Require Loss-Minimization Solutions. 2023.", url: "https://coresight.com/research/the-true-cost-of-apparel-returns-alarming-return-rates-require-loss-minimization-solutions/" },
  2: { text: "Google. Virtual apparel try-on in the UK and India. Google Shopping blog, December 2025.", url: "https://blog.google/products-and-platforms/products/shopping/virtual-apparel-try-on-uk-india/" },
  3: { text: "Alibaba Taobao. Tstars-Tryon 1.0. arXiv:2604.19748, April 2026.", url: arxiv("2604.19748") },
  4: { text: "Choi et al. VITON-HD: High-Resolution Virtual Try-On. CVPR 2021. Dataset licence CC BY-NC 4.0.", url: "https://github.com/shadow2496/VITON-HD" },
  5: { text: "Morelli et al. Dress Code: High-Resolution Multi-Category Virtual Try-On. ECCV 2022. Dataset access terms.", url: "https://github.com/aimagelab/dress-code" },
  6: { text: "Virtual Try-On for Cultural Clothing: A Benchmarking Study (BD-VITON). arXiv:2603.07291, March 2026. Paper licensed CC BY-NC-SA 4.0; no separate dataset licence stated.", url: arxiv("2603.07291") },
  7: { text: "FabricVTON. Internal technical documentation: What Is Built (updated 18 and 25 September 2026) and Project Status (24 September 2026). Available to reviewers on request." },
  8: { text: "National Retail Federation and Happy Returns. Consumers Expected to Return Nearly $850 Billion in Merchandise in 2025. Press release, 2025.", url: "https://nrf.com/media-center/press-releases/consumers-expected-to-return-nearly-850-billion-in-merchandise-in-2025" },
  9: { text: "Grand View Research. Virtual Fitting Room Market Size, Share and Trends Analysis Report, 2025 to 2030.", url: "https://www.grandviewresearch.com/industry-analysis/virtual-fitting-room-market" },
  10: { text: "Store Leads. Shopify Stores in the Apparel Category. Report as updated on 25 September 2026.", url: "https://storeleads.app/reports/shopify/category/Apparel" },
  11: { text: "Store Leads. WooCommerce Stores in the Apparel Category. Report as updated on 25 September 2026.", url: "https://storeleads.app/reports/woocommerce/category/Apparel" },
  12: { text: "TechCrunch. Google's new AI feature lets you virtually try on clothes. 24 July 2025.", url: "https://techcrunch.com/2025/07/24/googles-new-ai-feature-lets-you-virtually-try-on-clothes/" },
  13: { text: "Inditex. FY2025 Results. 2026.", url: "https://www.inditex.com/itxcomweb/us/en/press/news-detail/b870d5ec-6b7e-491d-b38e-340cd69036df/fy2025-results" },
  14: { text: "Google Cloud. Virtual Try-On on Vertex AI (virtual-try-on-001). Documentation.", url: "https://docs.cloud.google.com/vertex-ai/generative-ai/docs/models/imagen/virtual-try-on-preview-08-04" },
  15: { text: "JD.com. Oxygen-TryOn. arXiv:2607.21694, July 2026.", url: arxiv("2607.21694") },
  16: { text: "Feng, Chen, Shan and Kemelmacher-Shlizerman. Layering Virtual Try-On. ECCV 2026. arXiv:2607.22924.", url: arxiv("2607.22924") },
  17: { text: "Zhou et al. Learning Flow Fields in Attention for Controllable Person Image Generation (Leffa). CVPR 2025. arXiv:2412.08486.", url: arxiv("2412.08486") },
  18: { text: "Chong et al. CatVTON: Concatenation Is All You Need for Virtual Try-On with Diffusion Models. ICLR 2025. arXiv:2407.15886.", url: arxiv("2407.15886") },
  19: { text: "Rajput and Aneja. IndoFashion: Apparel Classification for Indian Ethnic Clothes. CVPR Workshops 2021. arXiv:2104.02830.", url: arxiv("2104.02830") },
  20: { text: "DIVA: Indian virtual try-on (IndicViton). ECCV 2024 Workshops, Springer.", url: "https://link.springer.com/chapter/10.1007/978-3-031-91569-7_23" },
  21: { text: "Awesome Try-On Models (curated list of try-on research), updated 3 September 2026.", url: "https://github.com/Zheng-Chong/Awesome-Try-On-Models" },
  22: { text: "SiCo: size-controllable virtual try-on. DIS 2025. arXiv:2408.02803.", url: arxiv("2408.02803") },
  23: { text: "Google. Generative virtual try-on for apparel in Google Shopping. June 2023.", url: "https://blog.google/products/shopping/ai-virtual-try-on-google-shopping/" },
  24: { text: "Monk, E. and Google. The Monk Skin Tone Scale.", url: "https://skintone.google/" },
  25: { text: "Xu et al. OOTDiffusion: Outfitting Fusion Based Latent Diffusion for Controllable Virtual Try-On. AAAI 2025. arXiv:2403.01779.", url: arxiv("2403.01779") },
  26: { text: "Choi et al. Improving Diffusion Models for Authentic Virtual Try-On in the Wild (IDM-VTON). ECCV 2024. arXiv:2403.05139.", url: arxiv("2403.05139") },
  27: { text: "Jiang et al. FitDiT: Advancing the Authentic Garment Details for High-Fidelity Virtual Try-On. arXiv:2411.10499.", url: arxiv("2411.10499") },
  28: { text: "Qwen Team. Qwen-Image-2.1 licence (Qwen Research License Agreement), September 2026.", url: "https://github.com/QwenLM/Qwen-Image-2.1/blob/main/LICENSE" },
  29: { text: "Black Forest Labs. FLUX.2 [klein] 9B licence (FLUX Non-Commercial License).", url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-9B/blob/main/LICENSE.md" },
  30: { text: "FASHN AI. FASHN VTON v1.5: Efficient Maskless Virtual Try-On in Pixel Space. Research page.", url: "https://fashn.ai/research/vton-1-5" },
  31: { text: "Zhu et al. TryOnDiffusion: A Tale of Two UNets. CVPR 2023. arXiv:2306.08276.", url: arxiv("2306.08276") },
  32: { text: "Morelli et al. LaDI-VTON: Latent Diffusion Textual-Inversion Enhanced Virtual Try-On. ACM MM 2023. arXiv:2305.13501.", url: arxiv("2305.13501") },
  33: { text: "Kim et al. StableVITON: Learning Semantic Correspondence with Latent Diffusion Model for Virtual Try-On. CVPR 2024. arXiv:2312.01725.", url: arxiv("2312.01725") },
  34: { text: "OmniTry: mask-free virtual try-on for wearable objects. arXiv:2508.13632.", url: arxiv("2508.13632") },
  35: { text: "Voost: a diffusion transformer for joint virtual try-on and try-off. SIGGRAPH Asia 2025. arXiv:2508.04825.", url: arxiv("2508.04825") },
  36: { text: "TAMF-VTON. arXiv:2607.14807, July 2026.", url: arxiv("2607.14807") },
  37: { text: "RealFit. arXiv:2609.25881, September 2026.", url: arxiv("2609.25881") },
  38: { text: "FastFit: cacheable multi-reference virtual try-on. arXiv:2508.20586.", url: arxiv("2508.20586") },
  39: { text: "CORAL: correspondence-aligned virtual try-on. arXiv:2602.17636, 2026.", url: arxiv("2602.17636") },
  40: { text: "FASHN AI. fashn-vton-1.5 model card, Hugging Face.", url: "https://huggingface.co/fashn-ai/fashn-vton-1.5" },
  41: { text: "VTEdit-Bench. ECCV 2026. arXiv:2603.11734.", url: arxiv("2603.11734") },
  42: { text: "TryOnReward. arXiv:2609.13259, September 2026.", url: arxiv("2609.13259") },
  43: { text: "DirectTryOn. arXiv:2605.12939, May 2026.", url: arxiv("2605.12939") },
  44: { text: "FASHN AI. Open-sourcing FASHN VTON v1.5. Blog post, 2026.", url: "https://fashn.ai/blog/fashn-vton-1-5-open-source-release" },
  45: { text: "FASHN AI. API pricing. Help centre.", url: "https://help.fashn.ai/plans-and-pricing/api-pricing" },
  46: { text: "ByteDance Seed. Seedream 4.0 officially released. September 2025.", url: "https://seed.bytedance.com/en/blog/seedream-4-0-officially-released-beyond-drawing-into-imagination" },
  47: { text: "Google Cloud. Virtual try-on technology with Google Cloud AI (Meesho case). July 2024.", url: "https://cloud.google.com/blog/products/ai-machine-learning/virtual-try-on-technology-with-google-cloud-ai" },
  48: { text: "Qwen Team. Qwen-Image-Edit-2511 model card (Apache-2.0).", url: "https://huggingface.co/Qwen/Qwen-Image-Edit-2511" },
  49: { text: "Black Forest Labs. FLUX.2 [klein] base 4B model card (Apache-2.0).", url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-base-4B" },
  50: { text: "Meituan LongCat. LongCat-Image-Edit model card.", url: "https://huggingface.co/meituan-longcat/LongCat-Image-Edit" },
  51: { text: "HiDream. HiDream-O1-Image model card (MIT).", url: "https://huggingface.co/HiDream-ai/HiDream-O1-Image" },
  52: { text: "Garments2Look. CVPR 2026. arXiv:2603.14153.", url: arxiv("2603.14153") },
  53: { text: "OpenVTON-Bench. arXiv:2601.22725, January 2026.", url: arxiv("2601.22725") },
  54: { text: "VTBench: a hierarchical virtual try-on benchmark. arXiv:2505.19571, May 2025.", url: arxiv("2505.19571") },
  55: { text: "VTONQA. arXiv:2601.02945, January 2026.", url: arxiv("2601.02945") },
  56: { text: "VTON-IQA and VTON-QBench. arXiv:2603.13057, March 2026.", url: arxiv("2603.13057") },
  57: { text: "Velioglu et al. TryOffDiff: virtual try-off with diffusion models. BMVC 2025. arXiv:2411.18350.", url: arxiv("2411.18350") },
  58: { text: "Karras et al. FIT: a fit-aware virtual try-on dataset. SIGGRAPH 2026. arXiv:2604.08526.", url: arxiv("2604.08526") },
  59: { text: "FitControler. ECCV 2026. arXiv:2512.24016.", url: arxiv("2512.24016") },
  60: { text: "BooW-VTON: mask-free in-the-wild virtual try-on. CVPR 2025. arXiv:2408.06047.", url: arxiv("2408.06047") },
  61: { text: "kohya-ss. musubi-tuner documentation for Qwen-Image training.", url: "https://github.com/kohya-ss/musubi-tuner/blob/main/docs/qwen_image.md" },
  62: { text: "LightX2V. Qwen-Image-Edit-2511-Lightning (few-step LoRA).", url: "https://huggingface.co/lightx2v/Qwen-Image-Edit-2511-Lightning" },
  63: { text: "CVPR 2027. Key dates.", url: "https://cvpr.thecvf.com/Conferences/2027/Dates" },
  64: { text: "NeurIPS 2026. Call for Evaluations and Datasets.", url: "https://neurips.cc/Conferences/2026/CallForEvaluationsDatasets" },
  65: { text: "Anusandhan National Research Foundation. Prime Minister Early Career Research Grant.", url: "https://anrfonline.in/ANRF/ecrg_anrf?HomePage=New" },
  66: { text: "Ministry of Electronics and Information Technology. TIDE 2.0 scheme.", url: "https://msh.meity.gov.in/schemes/tide" },
  67: { text: "IndiaAI Mission. Compute portal eligibility criteria.", url: "https://compute.indiaai.gov.in/eligibilitycriteria" },
  68: { text: "Startup India. Startup Schemes Playbook, June 2026.", url: "https://www.startupindia.gov.in/content/dam/startupindia/homebanners/Startup-Schemes-Playbook-June-2026.pdf" },
  69: { text: "EU Artificial Intelligence Act, Article 50: Transparency obligations.", url: "https://artificialintelligenceact.eu/article/50/" },
  70: { text: "Decart. Platform pricing: Lucy VTON realtime at USD 0.02 per second, 2026.", url: "https://docs.platform.decart.ai/getting-started/pricing" },
  71: { text: "LiveVVT: High-Fidelity Video Virtual Try-On in Real Time. arXiv:2608.26714, August 2026.", url: arxiv("2608.26714") },
  72: { text: "Decart. Realtime virtual try-on (Lucy VTON 3.5) documentation, 2026.", url: "https://docs.platform.decart.ai/models/realtime/virtual-try-on" },
  73: { text: "Decart. Decart raises USD 300M; over USD 450 million raised to date. May 2026.", url: "https://decart.ai/publications/decart-raises-300m-tech-leaders-back-the-company-as-both-customers-and-investors" },
  74: { text: "Google Labs. Doppl help centre: the app closed on 30 April 2026 and try-on moved into Search.", url: "https://support.google.com/labs/answer/16537062?hl=en" },
  75: { text: "FASHN AI. Image-to-Video API reference.", url: "https://docs.fashn.ai/api-reference/image-to-video" },
  76: { text: "Luma AI. Ray 3.2 video-to-video, May 2026.", url: "https://lumalabs.ai/learning-center/articles/ray-3-2-video-to-video" },
  77: { text: "Runway. Aleph 2.0 video editing.", url: "https://runway.com/product/aleph-2" },
  78: { text: "Fang et al. ViViD: Video Virtual Try-On using Diffusion Models. arXiv:2405.11794, 2024.", url: arxiv("2405.11794") },
  79: { text: "Chong et al. CatV2TON: temporal concatenation for image and video try-on. CVPR 2025 Workshops. arXiv:2501.11325.", url: arxiv("2501.11325") },
  80: { text: "MagicTryOn: video virtual try-on on Wan2.1. arXiv:2505.21325, 2025.", url: arxiv("2505.21325") },
  81: { text: "DreamVVT: keyframe-first video virtual try-on. ByteDance. arXiv:2508.02807, 2025.", url: arxiv("2508.02807") },
  82: { text: "KeyTailor: instruction-guided keyframes for video try-on. CVPR 2026. arXiv:2512.20340.", url: arxiv("2512.20340") },
  83: { text: "Vanast: animation and garment transfer from one image. CVPR 2026. arXiv:2604.04934.", url: arxiv("2604.04934") },
  84: { text: "BooM-VVT: mask-free video try-on with garment-sensitive keyframes. ACM MM 2026. arXiv:2609.04120.", url: arxiv("2609.04120") },
  85: { text: "UniVVT: video try-on without masks, pose or warping. arXiv:2608.05745, August 2026.", url: arxiv("2608.05745") },
  86: { text: "Vidu S2-Editing: real-time video editing adapted to causal streaming. arXiv:2609.11638, September 2026.", url: arxiv("2609.11638") },
  87: { text: "Yin et al. From Slow Bidirectional to Fast Autoregressive Video Diffusion Models (CausVid). arXiv:2412.07772.", url: arxiv("2412.07772") },
  88: { text: "Decart. MirageLSD: live stream diffusion technical report, July 2025 (archived copy).", url: "https://web.archive.org/web/20250918033439/https://about.decart.ai/publications/mirage" },
  89: { text: "Huang et al. Self Forcing: Bridging the Train-Test Gap in Autoregressive Video Diffusion. arXiv:2506.08009.", url: arxiv("2506.08009") },
  90: { text: "Decart. Lucy 2.5: raising the bar for live AI, July 2026.", url: "https://decart.ai/publications/lucy-2-5-raising-the-bar-for-live-ai" },
  91: { text: "ByteDance Seed. Seaweed APT2: autoregressive adversarial post-training for real-time video.", url: "https://seaweed-apt.com/2" },
  92: { text: "NVIDIA. LongLive: Real-time Interactive Long Video Generation. arXiv:2509.22622.", url: arxiv("2509.22622") },
  93: { text: "Krea. Krea Realtime 14B.", url: "https://www.krea.ai/blog/krea-realtime-14b" },
  94: { text: "StreamDiffusionV2. MLSys 2026. arXiv:2511.07399.", url: arxiv("2511.07399") },
  95: { text: "JD. JoyAI-Video-Edit: real-time instruction video editing (Apache-2.0). arXiv:2608.03974.", url: arxiv("2608.03974") },
  96: { text: "Pika. PikaStream 1.0: real-time video chat, April 2026.", url: "https://pika.art/blog/introducing-real-time-video-chat" },
  97: { text: "Wan Team. Wan2.1 open video foundation models (Apache-2.0).", url: "https://github.com/Wan-Video/Wan2.1" },
  98: { text: "Decart. Network requirements for realtime sessions.", url: "https://docs.platform.decart.ai/integrations/network-requirements" },
  99: { text: "Lightricks. LTX-2.x Community License.", url: "https://github.com/Lightricks/LTX-2/blob/main/LICENSE-2_x" },
  100: { text: "Tencent. HunyuanVideo 1.5 licence (Tencent Hunyuan Community License).", url: "https://github.com/Tencent-Hunyuan/HunyuanVideo-1.5/blob/master/LICENSE" },
  101: { text: "Wan Team. Wan2.2 and Wan2.2-Animate (Apache-2.0).", url: "https://huggingface.co/Wan-AI/Wan2.2-Animate-14B" },
  102: { text: "TripVVT: synthetic triplets for video try-on, and the TripVVT-10K dataset (CC BY-NC 4.0). arXiv:2604.27958.", url: arxiv("2604.27958") },
  103: { text: "MV-Fashion: multi-view studio fashion video dataset (CC BY-NC-SA 4.0). CVPR 2026. arXiv:2603.08147.", url: arxiv("2603.08147") },
  104: { text: "Shutterstock. Data licensing and the contributor fund.", url: "https://submit.shutterstock.com/help/en/articles/10594694-shutterstock-data-licensing-and-the-contributor-fund" },
  105: { text: "Pexels. Terms of service, including limits on machine-learning use.", url: "https://www.pexels.com/terms-of-service/" },
  106: { text: "Teed and Deng. RAFT optical flow (BSD-3-Clause).", url: "https://github.com/princeton-vl/RAFT" },
  107: { text: "Meta. SAM 2: Segment Anything in Images and Videos (Apache-2.0).", url: "https://github.com/facebookresearch/sam2" },
  108: { text: "OpenMMLab. MMPose and RTMPose (Apache-2.0).", url: "https://github.com/open-mmlab/mmpose" },
  109: { text: "LiveKit. Open-source WebRTC media server.", url: "https://github.com/livekit/livekit" },
  110: { text: "VBench: comprehensive benchmark suite for video generative models.", url: "https://github.com/Vchitect/VBench" },
  111: { text: "FabricVTON. Safety guardrails: research and implementation plan, 29 September 2026. Internal; available to reviewers on request." },
  112: { text: "NVIDIA. Inception programme for startups.", url: "https://www.nvidia.com/en-us/startups/" },
  113: { text: "Microsoft for Startups.", url: "https://learn.microsoft.com/en-us/startups" },
  114: { text: "AWS Activate credits.", url: "https://aws.amazon.com/startups/credits" },
  115: { text: "Google for Startups Cloud Program benefits.", url: "https://cloud.google.com/startup/benefits" },
  116: { text: "Google for Startups Accelerator: India.", url: "https://startup.google.com/programs/accelerator/india" },
  117: { text: "H&M Foundation. Global Change Award 2027, via The Mills Fabrica.", url: "https://themillsfabrica.com/events/global-change-award-2027" },
  118: { text: "LVMH. La Maison des Startups and technology partners.", url: "https://www.lvmh.com/en/startups-tech-partners" },
  119: { text: "Chen et al. Mind the Trojan Horse: Image Prompt Adapter Enabling Scalable and Deceptive Jailbreaking. CVPR 2025. arXiv:2504.05838.", url: arxiv("2504.05838") },
};

export const DOC_REF_COUNT = Object.keys(DOC_REFS).length;
